apiVersion: apps/v1
kind: Deployment
metadata:
  name: kub-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kub-test
  template:
    metadata:
      labels:
        app: kub-test
    spec:
      containers:
        - name: kub-test
          image: altjin09/kub_test:latest
          ports:
            - containerPort: 5000
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: "http://signoz-otel-collector.platform:4317"
            - name: OTEL_EXPORTER_OTLP_INSECURE
              value: "true"
