apiVersion: v1
kind: Service
metadata:
  name: kub-test-service
spec:
  type: NodePort
  selector:
    app: kub-test
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 32668
  type: NodePort
